const HOSTELS = {
  boys: { name: "Boys Hostel", short: "Boys", icon: "👦", accent: "blue", machines: ["B-01", "B-02", "B-03", "B-04", "B-05", "B-06"] },
  girls: { name: "Girls Hostel", short: "Girls", icon: "👧", accent: "purple", machines: ["G-01", "G-02", "G-03", "G-04", "G-05", "G-06"] }
};
const TIMES = ["5:00 PM – 6:00 PM", "6:00 PM – 7:00 PM", "7:00 PM – 8:00 PM", "8:00 PM – 9:00 PM"];
const today = new Date(); const dateKey = d => d.toISOString().slice(0, 10);
const todayKey = dateKey(today); const formatDate = value => new Date(`${value}T12:00:00`).toLocaleDateString("en-US", { day: "numeric", month: "long", year: "numeric" });
const relativeDate = value => value === todayKey ? "Today" : value === dateKey(new Date(today.getTime() + 86400000)) ? "Tomorrow" : formatDate(value);
const initialBookings = [
  { id: "WM-1024", hostel: "boys", machine: "B-02", date: todayKey, time: TIMES[1], status: "CONFIRMED", student: "Arun Kumar" },
  { id: "WM-1025", hostel: "boys", machine: "B-04", date: dateKey(new Date(today.getTime() + 86400000)), time: TIMES[2], status: "CONFIRMED", student: "Arun Kumar" },
  { id: "WM-1019", hostel: "girls", machine: "G-03", date: todayKey, time: TIMES[0], status: "CONFIRMED", student: "Maya Shah" }
];
const savedBookings = JSON.parse(localStorage.getItem("washmate-bookings") || "null");
const state = { hostel: localStorage.getItem("washmate-hostel") || "boys", bookings: savedBookings || initialBookings, route: location.hash.slice(1) || "home", modal: null, calendarDate: new Date(today.getFullYear(), today.getMonth(), 1), selectedDate: todayKey, filter: "all", adminHostel: "boys" };
function save() { localStorage.setItem("washmate-bookings", JSON.stringify(state.bookings)); localStorage.setItem("washmate-hostel", state.hostel); }
function hostel() { return HOSTELS[state.hostel]; }
function bookingsFor(h = state.hostel) { return state.bookings.filter(b => b.hostel === h); }
function activeBookings(h = state.hostel) { return bookingsFor(h).filter(b => b.status === "CONFIRMED"); }
function isBooked(machine, date, time, h = state.hostel) { return state.bookings.some(b => b.hostel === h && b.machine === machine && b.date === date && b.time === time && b.status === "CONFIRMED"); }
function setRoute(route) { state.route = route; location.hash = route; render(); window.scrollTo({ top: 0, behavior: "smooth" }); }
function toast(message) { const el = document.createElement("div"); el.className = "toast"; el.textContent = message; document.getElementById("toast-region").append(el); setTimeout(() => el.classList.add("out"), 2700); setTimeout(() => el.remove(), 3000); }
function statusBadge(status) { const labels = { available: "🟢 AVAILABLE", booked: "🟡 BOOKED", maintenance: "🔴 MAINTENANCE" }; return `<span class="status-badge status-${status}">${labels[status]}</span>`; }
function machineStatus(machine, h = state.hostel) {
  if (machine.endsWith("03")) return "maintenance";
  if (isBooked(machine, todayKey, TIMES[1], h)) return "booked";
  return "available";
}
function render() {
  const app = document.getElementById("app"); document.querySelectorAll("[data-route]").forEach(a => a.classList.toggle("active", a.dataset.route === state.route));
  document.getElementById("nav-count").textContent = bookingsFor().filter(b => b.student === "Arun Kumar" && b.status === "CONFIRMED").length;
  document.getElementById("topbar-hostel").textContent = state.route === "home" ? "All hostels" : hostel().name;
  document.getElementById("topbar-date").textContent = today.toLocaleDateString("en-US", { weekday: "short", month: "short", day: "numeric" });
  const pages = { home: homePage, dashboard: dashboardPage, machines: machinesPage, bookings: bookingsPage, profile: profilePage, admin: adminPage };
  app.innerHTML = (pages[state.route] || dashboardPage)(); bindPageEvents();
}
function homePage() {
  return `<div class="page"><section class="hero"><div><p class="eyebrow">Your laundry, on your time</p><h1>Your Laundry.<br><em>Your Slot.</em><br>Zero Waiting.</h1><p>Book a washing machine in seconds and never wait around for an empty machine again.</p><button class="btn btn-primary" data-action="choose-hostel">Book Your Slot&nbsp; →</button><div class="hero-note"><span>✦</span><span><strong>12 machines</strong> across both hostels · open today</span></div></div><div class="hero-art"><span class="floating-bubble bubble-1"></span><span class="floating-bubble bubble-2"></span><span class="floating-bubble bubble-3"></span><div class="washer-illustration"><div class="washer-top"></div><div class="washer-window">🫧</div></div></div></section><div class="section-title"><h2>Choose your hostel</h2><span class="eyebrow">Separate spaces, same easy flow</span></div><div class="hostel-grid"><div class="hostel-card boys" data-hostel="boys"><span class="hostel-emoji">👦</span><h3>Boys Hostel</h3><p>6 machines · 4 available today</p><span class="card-link">View machines&nbsp; →</span></div><div class="hostel-card girls" data-hostel="girls"><span class="hostel-emoji">👧</span><h3>Girls Hostel</h3><p>6 machines · 4 available today</p><span class="card-link">View machines&nbsp; →</span></div></div></div>`;
}
function stats(h = state.hostel) {
  const statuses = HOSTELS[h].machines.map(m => machineStatus(m, h)); return { available: statuses.filter(s => s === "available").length, booked: statuses.filter(s => s === "booked").length, maintenance: statuses.filter(s => s === "maintenance").length, mine: activeBookings(h).filter(b => b.student === "Arun Kumar").length };
}
function statsMarkup(h = state.hostel) { const s = stats(h); return `<div class="stats-grid"><div class="stat-card accent-green"><span class="stat-icon">🟢</span><div class="stat-value">${s.available}</div><div class="stat-label">Available machines</div></div><div class="stat-card accent-yellow"><span class="stat-icon">🟡</span><div class="stat-value">${s.booked}</div><div class="stat-label">Booked today</div></div><div class="stat-card accent-blue"><span class="stat-icon">🔵</span><div class="stat-value">${s.mine}</div><div class="stat-label">My bookings</div></div><div class="stat-card accent-red"><span class="stat-icon">🔴</span><div class="stat-value">${s.maintenance}</div><div class="stat-label">Maintenance</div></div></div>`; }
function dashboardPage() { return `<div class="page"><div class="page-heading"><div><p class="eyebrow">${hostel().icon} ${hostel().name}</p><h1>Good afternoon, Student! 👋</h1><p>Your laundry dashboard is looking fresh.</p></div><button class="btn btn-primary" data-action="book-first">Book a machine&nbsp; →</button></div>${statsMarkup()}<div class="dashboard-layout"><div class="panel"><div class="panel-heading"><div><h2>Today's laundry schedule</h2><p>Evening availability at a glance</p></div><a href="#machines">See all</a></div><div class="filter-row" style="margin-bottom:8px">${["all","available","booked","maintenance"].map(f => `<button class="filter-btn ${state.filter === f ? "active" : ""}" data-filter="${f}">${f[0].toUpperCase()+f.slice(1)}</button>`).join("")}</div>${scheduleRows()}</div><div><div class="panel"><div class="panel-heading"><div><h2>Pick a date</h2><p>${formatDate(state.selectedDate)}</p></div></div>${calendarMarkup()}</div><div class="panel"><div class="panel-heading"><h2>Quick tip</h2><span>💡</span></div><p style="color:var(--muted);line-height:1.6;font-size:12px">Evening slots fill up fast. Lock in your preferred time before heading to the laundry room.</p></div></div></div></div>`; }
function scheduleRows() { const rows = []; hostel().machines.slice(0, 4).forEach((m, i) => rows.push({ time: TIMES[i], machine: m, status: i === 2 ? "maintenance" : i === 1 ? "booked" : "available" })); return rows.filter(r => state.filter === "all" || r.status === state.filter).map(r => `<div class="schedule-row"><span class="schedule-time">${r.time.split(" – ")[0]}</span><span class="schedule-machine">${r.machine}</span>${statusBadge(r.status)}</div>`).join("") || `<div class="empty-state"><div class="empty-icon">🫧</div><p>No matching slots right now.</p></div>`; }
function calendarMarkup() { const y = state.calendarDate.getFullYear(), m = state.calendarDate.getMonth(), first = new Date(y,m,1).getDay(), days = new Date(y,m+1,0).getDate(); let out = `<div style="display:flex;justify-content:space-between;align-items:center;margin-bottom:13px"><button class="filter-btn" data-cal="prev">←</button><strong>${state.calendarDate.toLocaleDateString("en-US",{month:"long",year:"numeric"})}</strong><button class="filter-btn" data-cal="next">→</button></div><div class="calendar">${["S","M","T","W","T","F","S"].map(d => `<div class="calendar-day-name">${d}</div>`).join("")}`; for (let i=0;i<first;i++) out += `<div class="calendar-day empty"></div>`; for (let d=1;d<=days;d++) { const key = dateKey(new Date(y,m,d)), has = hostel().machines.some(machine => TIMES.some(time => !isBooked(machine,key,time))); out += `<button class="calendar-day ${key===todayKey?"today ":""}${key===state.selectedDate?"selected":""}" data-date="${key}">${d}${has?'<span class="calendar-dot"></span>':""}</button>`; } return out + "</div>"; }
function machineCards(h = state.hostel) { return `<div class="machine-grid">${HOSTELS[h].machines.map(machine => { const status = machineStatus(machine,h); const current = bookingsFor(h).find(b => b.machine === machine && b.date === todayKey && b.status === "CONFIRMED"); return `<article class="machine-card"><div class="machine-head"><div class="machine-icon ${status === "booked" ? "running" : ""}">🧺</div>${statusBadge(status)}</div><div class="machine-code">${machine}</div><div class="machine-name">Washing Machine</div><div class="machine-info">${status === "maintenance" ? "Expected back" : current ? "Today" : "Next available"}<strong>${status === "maintenance" ? "Tomorrow morning" : current ? current.time : TIMES[0]}</strong></div><button class="btn ${status === "available" ? "btn-primary" : "btn-secondary"} machine-action" data-machine="${machine}" ${status !== "available" ? "disabled" : ""}>${status === "available" ? "Book now" : status === "booked" ? "Booked" : "Unavailable"}</button></article>`; }).join("")}</div>`; }
function machinesPage() { return `<div class="page"><div class="page-heading"><div><p class="eyebrow">${hostel().icon} ${hostel().name}</p><h1>Machines</h1><p>Find your next free cycle at a glance.</p></div><div class="hostel-switch"><button class="${state.hostel==="boys"?"active":""}" data-switch-hostel="boys">👦 Boys</button><button class="${state.hostel==="girls"?"active":""}" data-switch-hostel="girls">👧 Girls</button></div></div>${machineCards()}</div>`; }
function bookingsPage() { const mine = state.bookings.filter(b => b.student === "Arun Kumar" && b.status === "CONFIRMED"); return `<div class="page"><div class="page-heading"><div><p class="eyebrow">Your laundry history</p><h1>My Laundry Bookings</h1><p>Keep track of your upcoming wash cycles.</p></div><button class="btn btn-primary" data-action="book-first">Book another&nbsp; +</button></div><div class="booking-list">${mine.length ? mine.map(b => `<article class="booking-card"><div class="booking-machine">${b.machine}</div><div><h3>${relativeDate(b.date)} · ${b.time}</h3><p>${HOSTELS[b.hostel].icon} ${HOSTELS[b.hostel].name} · Booking ${b.id}</p></div><div class="booking-meta">${statusBadge("available").replace("AVAILABLE","CONFIRMED").replace("status-available","status-available")}<small><button class="btn btn-danger btn-small" data-cancel="${b.id}">Cancel booking</button></small></div></article>`).join("") : `<div class="panel"><div class="empty-state"><div class="empty-icon">🧺</div><h3>No bookings yet</h3><p>Your next laundry day is just one click away.</p><button class="btn btn-primary" data-action="book-first" style="margin-top:17px">Find a machine</button></div></div>`}</div></div>`; }
function profilePage() { return `<div class="page"><div class="page-heading"><div><p class="eyebrow">Account</p><h1>Your profile</h1><p>Just enough detail to keep your bookings personal.</p></div></div><div class="profile-card"><div class="profile-header"><div class="profile-avatar">AK</div><div><h2>Arun Kumar</h2><p>Student · ${HOSTELS[state.hostel].name}</p></div></div><div class="profile-details"><div><span class="detail-label">Student ID</span><span class="detail-value">STU1024</span></div><div><span class="detail-label">Hostel</span><span class="detail-value">${HOSTELS[state.hostel].name}</span></div><div><span class="detail-label">Room number</span><span class="detail-value">B-204</span></div><div><span class="detail-label">Email</span><span class="detail-value">arun.kumar@student.edu</span></div></div><div class="profile-actions"><button class="btn btn-primary" data-action="edit-profile">Edit profile</button><button class="btn btn-secondary" data-action="logout">Log out</button></div></div></div>`; }
function adminPage() { const h = state.adminHostel, s = stats(h); return `<div class="page"><div class="page-heading"><div><p class="eyebrow">Demo controls</p><h1>Admin dashboard</h1><p>One clear view across both laundry rooms.</p></div><button class="btn btn-primary" data-action="add-machine">＋ Add machine</button></div><div class="stats-grid admin-stats"><div class="stat-card"><div class="stat-value">12</div><div class="stat-label">Total machines</div></div><div class="stat-card accent-green"><div class="stat-value">${s.available*2}</div><div class="stat-label">Available</div></div><div class="stat-card accent-yellow"><div class="stat-value">${s.booked*2}</div><div class="stat-label">Booked</div></div><div class="stat-card accent-red"><div class="stat-value">2</div><div class="stat-label">Maintenance</div></div><div class="stat-card accent-blue"><div class="stat-value">${state.bookings.length}</div><div class="stat-label">Today's bookings</div></div></div><div class="panel"><div class="panel-heading"><div class="hostel-switch"><button class="${h==="boys"?"active":""}" data-admin-hostel="boys">BOYS HOSTEL</button><button class="${h==="girls"?"active":""}" data-admin-hostel="girls">GIRLS HOSTEL</button></div></div><div class="table-wrap"><table class="data-table"><thead><tr><th>Machine</th><th>Status</th><th>Current booking</th><th>Next available</th><th>Action</th></tr></thead><tbody>${HOSTELS[h].machines.map(m => { const st=machineStatus(m,h), b=bookingsFor(h).find(x=>x.machine===m&&x.date===todayKey); return `<tr><td><strong>${m}</strong></td><td>${statusBadge(st)}</td><td>${b ? b.time : "—"}</td><td>${st==="maintenance"?"Tomorrow":TIMES[0]}</td><td><button class="btn btn-secondary btn-small" data-action="admin-toggle" data-machine="${m}">${st==="maintenance"?"Mark available":"Edit"}</button></td></tr>`; }).join("")}</tbody></table></div></div><div class="panel"><div class="panel-heading"><h2>Recent bookings</h2><p>Latest activity</p></div><div class="table-wrap"><table class="data-table"><thead><tr><th>Student</th><th>Hostel</th><th>Machine</th><th>Date</th><th>Time</th><th>Status</th></tr></thead><tbody>${state.bookings.slice().reverse().map(b => `<tr><td>${b.student}</td><td>${HOSTELS[b.hostel].name}</td><td>${b.machine}</td><td>${relativeDate(b.date)}</td><td>${b.time}</td><td>${b.status}</td></tr>`).join("")}</tbody></table></div></div></div>`; }
function bookingModal(machine) { state.modal = { machine, date: state.selectedDate, time: null }; const available = TIMES.map(t => `<button class="slot-btn" data-slot="${t}" ${isBooked(machine,state.selectedDate,t) ? "disabled" : ""}>${t}</button>`).join(""); return `<div class="modal"><div class="modal-header"><div><p class="eyebrow">Quick booking</p><h2>Book washing machine</h2></div><button class="modal-close" data-action="close-modal">×</button></div><div><span class="form-label">Machine</span><strong>${machine} · ${hostel().name}</strong><label class="form-label" for="booking-date">Select date</label><input class="date-input" id="booking-date" type="date" min="${todayKey}" value="${state.selectedDate}"><span class="form-label">Select time</span><div class="slots">${available}</div><div class="modal-summary">Machine: <strong>${machine}</strong><br>Date: <strong id="summary-date">${relativeDate(state.selectedDate)}</strong><br>Time: <strong id="summary-time">Choose a slot</strong></div><button class="btn btn-primary modal-submit" data-action="confirm-booking" disabled>Confirm booking&nbsp; →</button></div></div>`; }
function showModal(content) { const root=document.getElementById("modal-root"); root.innerHTML=content; root.hidden=false; }
function successModal(booking) { return `<div class="modal success-modal"><span class="confetti"></span><span class="confetti"></span><span class="confetti"></span><div class="success-emoji">🎉</div><h2>Slot booked successfully!</h2><p>Your laundry plan is looking fresh.</p><div class="success-details"><div><span>Machine</span><strong>${booking.machine}</strong></div><div><span>Date</span><strong>${formatDate(booking.date)}</strong></div><div><span>Time</span><strong>${booking.time}</strong></div><div><span>Booking ID</span><strong>${booking.id}</strong></div></div><div class="success-actions"><button class="btn btn-primary" data-action="view-bookings">View my bookings</button><button class="btn btn-secondary" data-action="close-modal">Close</button></div></div>`; }
function bindPageEvents() { document.querySelectorAll("[data-hostel]").forEach(el => el.onclick=()=>{state.hostel=el.dataset.hostel;save();setRoute("dashboard");}); document.querySelectorAll("[data-switch-hostel]").forEach(el=>el.onclick=()=>{state.hostel=el.dataset.switchHostel;save();render();}); document.querySelectorAll("[data-machine]").forEach(el=>el.onclick=()=>{state.selectedDate=todayKey;showModal(bookingModal(el.dataset.machine));}); document.querySelectorAll("[data-filter]").forEach(el=>el.onclick=()=>{state.filter=el.dataset.filter;render();}); document.querySelectorAll("[data-date]").forEach(el=>el.onclick=()=>{state.selectedDate=el.dataset.date;render();}); document.querySelectorAll("[data-cal]").forEach(el=>el.onclick=()=>{state.calendarDate.setMonth(state.calendarDate.getMonth()+(el.dataset.cal==="next"?1:-1));render();}); document.querySelectorAll("[data-cancel]").forEach(el=>el.onclick=()=>{state.bookings=state.bookings.filter(b=>b.id!==el.dataset.cancel);save();toast("✅ Booking cancelled.");render();}); document.querySelectorAll("[data-admin-hostel]").forEach(el=>el.onclick=()=>{state.adminHostel=el.dataset.adminHostel;render();}); }
function actions(action) { if(action==="choose-hostel"){setRoute("machines");return;} if(action==="book-first"){showModal(bookingModal(hostel().machines.find(m=>machineStatus(m)==="available")||hostel().machines[0]));return;} if(action==="close-modal"){document.getElementById("modal-root").hidden=true;return;} if(action==="view-bookings"){document.getElementById("modal-root").hidden=true;setRoute("bookings");return;} if(action==="edit-profile"){toast("Profile editing is ready for this demo.");return;} if(action==="logout"){toast("Demo logout complete — see you soon!");return;} if(action==="add-machine"){toast("Demo mode keeps the machine list at 12.");return;} if(action==="admin-toggle"){toast("Machine status updated for this demo.");return;} }
document.addEventListener("click", e=>{ const slot=e.target.closest("[data-slot]"); if(slot && state.modal){state.modal.time=slot.dataset.slot;document.querySelectorAll("[data-slot]").forEach(s=>s.classList.toggle("selected",s===slot));document.getElementById("summary-time").textContent=slot.dataset.slot;document.querySelector("[data-action=confirm-booking]").disabled=false;} const date=e.target.closest("#booking-date"); if(date){date.onchange=()=>{state.modal.date=date.value;document.getElementById("summary-date").textContent=relativeDate(date.value);document.querySelectorAll("[data-slot]").forEach(s=>{s.disabled=isBooked(state.modal.machine,date.value,s.dataset.slot);});};} const confirm=e.target.closest("[data-action=confirm-booking]"); if(confirm && state.modal && state.modal.time){if(isBooked(state.modal.machine,state.modal.date,state.modal.time)){toast("⚠️ That slot is already booked.");return;} const booking={id:`WM-${1026+state.bookings.length}`,hostel:state.hostel,machine:state.modal.machine,date:state.modal.date,time:state.modal.time,status:"CONFIRMED",student:"Arun Kumar"};state.bookings.push(booking);save();toast(`🎉 ${booking.machine} booked successfully!`);showModal(successModal(booking));return;} const action=e.target.closest("[data-action]"); if(action) actions(action.dataset.action); });
document.querySelectorAll("[data-route]").forEach(a=>a.addEventListener("click",()=>{state.route=a.dataset.route;document.getElementById("sidebar").classList.remove("open");setTimeout(render,0);})); document.getElementById("mobile-menu").onclick=()=>document.getElementById("sidebar").classList.toggle("open"); document.getElementById("theme-toggle").onclick=()=>{document.body.classList.toggle("dark");localStorage.setItem("washmate-theme",document.body.classList.contains("dark")?"dark":"light");}; document.getElementById("profile-button").onclick=()=>setRoute("profile"); document.getElementById("notification-button").onclick=()=>toast("🔔 You’re all caught up."); window.addEventListener("hashchange",()=>{state.route=location.hash.slice(1)||"home";render();}); if(localStorage.getItem("washmate-theme")==="dark")document.body.classList.add("dark"); render();
